-- 원생 테이블
-- 원생 번호, 이름, 성별, 주민등록번호, 입관일자, 띠
CREATE TABLE STUDENT(
	STUDENT_NO NUMBER PRIMARY KEY,
	STUDENT_NM VARCHAR2(30) NOT NULL,
	STUDENT_GENDER CHAR(1) CHECK( STUDENT_GENDER IN ('M', 'F') ),
	STUDENT_SSN CHAR(14),
	STUDENT_DATE DATE DEFAULT SYSDATE,
	STUDENT_BELT VARCHAR2(20)
);

ALTER TABLE STUDENT MODIFY STUDENT_SECESSION_FL DEFAULT 'N';

COMMENT ON COLUMN STUDENT.STUDENT_NO IS '원생 번호';
COMMENT ON COLUMN STUDENT.STUDENT_NM IS '원생 이름';
COMMENT ON COLUMN STUDENT.STUDENT_GENDER IS '원생 성별';
COMMENT ON COLUMN STUDENT.STUDENT_SSN IS '원생 주민등록번호';
COMMENT ON COLUMN STUDENT.STUDENT_DATE IS '입관 일자';
COMMENT ON COLUMN STUDENT.STUDENT_BELT IS '원생 띠';
COMMENT ON COLUMN STUDENT.STUDENT_SECESSION_FL IS '탈퇴여부(Y/N)' ;

-- 원생 번호 시퀀스 생성
CREATE SEQUENCE SEQ_STUDENT_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

-- 원생 정보 추가 INSERT 
INSERT INTO "STUDENT"
VALUES('1111', '학생1', 'M', '150212-3012011', '2022-05-13', '흰띠')

INSERT INTO "STUDENT"
VALUES('2222', '학생2', 'F', '170212-4018511', '2022-09-18', '노란띠')

INSERT INTO "STUDENT"
VALUES('6666', '학생6', 'M', '100517-3145658', '2020-08-19', '검정띠', DEFAULT)

SELECT * FROM STUDENT

-- 원생 정보 수정
UPDATE "STUDENT" SET
STUDENT_NM = '학생1',
STUDENT_BELT = '주황띠'
WHERE STUDENT_NO = 1111;

UPDATE "STUDENT" SET
STUDENT_SECESSION_FL = 'N'
WHERE STUDENT_NO = 5555;

SELECT STUDENT_SECESSION
FROM STUDENT;


-- 원생 퇴원(SECESSION_FL 컬럼의 값을 'Y'로 변경)
UPDATE STUDENT SET
SECESSION_FL = 'Y'
WHERE MEMBER_NM = ?;
