-- 도장 테이블
-- 도장 번호, 아이디, 비밀번호, 체육관이름, 관장이름, 학생 수, 가입일, 탈퇴여부
CREATE TABLE MASTER(
	MASTER_NO NUMBER PRIMARY KEY,
	MASTER_ID VARCHAR2(30) NOT NULL,
	MASTER_PW VARCHAR2(30) NOT NULL,
	GYM_NM VARCHAR2(30) NOT NULL,
	MASTER_NM VARCHAR2(30) NOT NULL,
	STUDENT_COUNT NUMBER,
	ENROLL_DATE DATE DEFAULT SYSDATE,
	SECESSION_FL CHAR(1) DEFAULT 'N' CHECK( SECESSION_FL IN ('Y', 'N') )
);


-- 회원 번호 시퀀스 생성
CREATE SEQUENCE SEQ_MASTER_NO 
START WITH 1
INCREMENT BY 1
NOCYCLE 
NOCACHE;


COMMENT ON COLUMN MASTER.MASTER_NO IS '회원 번호';
COMMENT ON COLUMN MASTER.MASTER_ID IS '회원 아이디';
COMMENT ON COLUMN MASTER.MASTER_PW IS '회원 비밀번호';
COMMENT ON COLUMN MASTER.GYM_NM IS '체육관 이름';
COMMENT ON COLUMN MASTER.MASTER_NM IS '회원 이름';
COMMENT ON COLUMN MASTER.STUDENT_COUNT IS '원생 수';
COMMENT ON COLUMN MASTER.ENROLL_DATE IS '회원 가입일';
COMMENT ON COLUMN MASTER.SECESSION_FL IS '탈퇴여부(Y/N)';

-- 회원 가입 INSERT 
INSERT INTO "MASTER"
VALUES( SEQ_MASTER_NO.NEXTVAL,'skk11', 'pass01', '성균관', '유저일', '200', DEFAULT, DEFAULT);

INSERT INTO "MASTER"
VALUES( SEQ_MASTER_NO.NEXTVAL, 'abc22', 'pass02', '숭인', '유저이', '150', DEFAULT, DEFAULT);

INSERT INTO "MASTER"
VALUES( SEQ_MASTER_NO.NEXTVAL, 'abc33', 'pass03', '엘리트', '유저3', '120', DEFAULT, DEFAULT);
	

SELECT * FROM "MASTER";

COMMIT;

-- 아이디 중복 확인
-- (중복되는 아이디가 입력되어도 탈퇴한 계정이면 중복X)
SELECT COUNT(*) FROM "MASTER"
WHERE MASTER_ID = 'abc22'
AND SECESSION_FL = 'N';
--> ID가 user01 이면서 탈퇴하지 않은 회원 조회

-- 중복이면 1, 아니면 0 조회

SELECT * FROM "MASTER";

-- 로그인(아이디, 비밀번호가 일치 +  탈퇴X 회원)
SELECT MASTER_ID, GYM_NM, MEMBER_NM, STUDENT_COUNT, 
	TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') ENROLL_DATE
FROM MASTER
WHERE MASTER_ID = 'user01'
AND MASTER_PW = 'pass01'
AND SECESSION_FL = 'N';

-- 회원 정보 수정(체육관 이름, 원생 수)
UPDATE MASTER SET
GYM_NM = ?,  
STUDENT_COUNT = ?    
WHERE MASTER_NM = ?;

-- 비밀번호 변경
UPDATE MASTER SET
MASTER_PW = ?
WHERE MASTER_ID = ?
AND MASTER_PW  = ?

-- 회원 탈퇴(SECESSION_FL 컬럼의 값을 'Y'로 변경)
UPDATE MASTER SET
SECESSION_FL = 'Y'
WHERE MASTER_NM = ?;
AND MASTER_PW = ?;



-----------------------------------------------------------------------------------------
-- 원생 테이블
-- 원생 번호, 이름, 성별, 주민등록번호, 입관일자, 띠, 소속 체육관, 퇴원여부
CREATE TABLE STUDENT(
	STUDENT_NO NUMBER PRIMARY KEY,
	MASTER_NO NUMBER REFERENCES MASTER(MASTER_NO),
	STUDENT_NM VARCHAR2(30),
	STUDENT_GENDER CHAR(1)  CHECK( STUDENT_GENDER IN ('M', 'F') ),
	STUDENT_SSN CHAR(14),
	STUDENT_DATE DATE DEFAULT SYSDATE,
	STUDENT_BELT VARCHAR2(20),
	STUDENT_SECESSION_FL CHAR(1) DEFAULT 'N' CHECK( STUDENT_SECESSION_FL IN ('Y','N') )
);

DROP TABLE STUDENT ;

COMMENT ON COLUMN STUDENT.STUDENT_NO IS '원생 번호';
COMMENT ON COLUMN STUDENT.MASTER_NO IS '도장 번호';
COMMENT ON COLUMN STUDENT.STUDENT_NM IS '원생 이름';
COMMENT ON COLUMN STUDENT.STUDENT_GENDER IS '원생 성별';
COMMENT ON COLUMN STUDENT.STUDENT_SSN IS '원생 주민등록번호';
COMMENT ON COLUMN STUDENT.STUDENT_DATE IS '입관 일자';
COMMENT ON COLUMN STUDENT.STUDENT_BELT IS '원생 띠';
COMMENT ON COLUMN STUDENT.STUDENT_SECESSION_FL IS '탈퇴여부(Y/N)' ;

-- 원생 번호 시퀀스 생성
CREATE SEQUENCE SEQ_STUDENT_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

-- 원생 정보 추가 INSERT 
INSERT INTO "STUDENT"
VALUES('1111', '1', '학생1', 'M', '150212-3012011', '2022-05-13', '흰띠', DEFAULT);

INSERT INTO "STUDENT"
VALUES('2222', '2', '학생2', 'F', '170212-4018511', '2022-09-18', '노란띠', DEFAULT);

INSERT INTO "STUDENT"
VALUES('3333', '3', '학생3', 'M', '100517-3145658', '2020-08-19', '검정띠', DEFAULT);

SELECT * FROM STUDENT

-- 원생 정보 수정
UPDATE "STUDENT" SET
STUDENT_NM = '학생1',
STUDENT_BELT = '주황띠'
WHERE STUDENT_NO = 1111;

UPDATE "STUDENT" SET
STUDENT_SECESSION_FL = 'N'
WHERE STUDENT_NO = 1111;

SELECT *
FROM STUDENT;


-- 원생 퇴원(SECESSION_FL 컬럼의 값을 'Y'로 변경)
UPDATE STUDENT SET
STUDENT_SECESSION_FL = 'Y'
WHERE STUDENT_NM = ?;

------------------------------------------------------------------------------------------
-- 심사 테이블
-- 심사이름, 심사일자, 원생 번호, 원생 띠, 참석여부, 미납여부
CREATE TABLE TEST (
	TEST_NO NUMBER PRIMARY KEY,
	TEST_NM VARCHAR2(30) NOT NULL,
	TEST_DATE DATE,
	STUDENT_NO NUMBER REFERENCES STUDENT(STUDENT_NO),
	TEST_ATTENDANCE CHAR(1) DEFAULT 'N' CHECK( TEST_ATTENDANCE IN ('Y', 'N') ),
	TEST_PAY CHAR(1) DEFAULT 'N' CHECK( TEST_PAY IN ('Y', 'N') )
);

DROP TABLE TEST;

COMMENT ON COLUMN TEST.TEST_NO IS '심사 번호';
COMMENT ON COLUMN TEST.TEST_NM IS '심사 이름';
COMMENT ON COLUMN TEST.TEST_DATE IS '심사 일자';
COMMENT ON COLUMN TEST.STUDENT_NO IS '원생 번호';
COMMENT ON COLUMN TEST.TEST_ATTENDANCE IS '참석 여부';
COMMENT ON COLUMN TEST.TEST_PAY IS '미납 여부';

-- 원생 번호 시퀀스 생성
CREATE SEQUENCE SEQ_TEST_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

INSERT INTO TEST 
VALUES(SEQ_TEST_NO.NEXTVAL, '333회', '2022-10-28', '1111', DEFAULT, DEFAULT);

INSERT INTO TEST 
VALUES(SEQ_TEST_NO.NEXTVAL,'333회', '2022-10-28', '2222', DEFAULT, DEFAULT);

INSERT INTO TEST 
VALUES(SEQ_TEST_NO.NEXTVAL,'333회', '2022-10-28', '3333', DEFAULT, DEFAULT);

INSERT INTO TEST 
VALUES(SEQ_TEST_NO.NEXTVAL,'332회', '2022-08-28', '3333', DEFAULT, DEFAULT);

INSERT INTO TEST 
VALUES(SEQ_TEST_NO.NEXTVAL,'331회', '2022-06-28', '2222', DEFAULT, DEFAULT);

INSERT INTO TEST 
VALUES(SEQ_TEST_NO.NEXTVAL,'331회', '2022-06-28', '1111', DEFAULT, DEFAULT);


SELECT * FROM TEST;

-- 심사 이름별 원생 조회
SELECT TEST_NM, TEST_DATE, STUDENT_NM, STUDENT_BELT, STUDENT_SECESSION_FL 
FROM TEST
JOIN STUDENT USING(STUDENT_NO)
WHERE TEST_NM = '331회';



SELECT TEST_NM, TEST_DATE, STUDENT_NM, STUDENT_BELT, STUDENT_DATE, STUDENT_SECESSION_FL 
FROM TEST
JOIN STUDENT USING(STUDENT_NO)

SELECT STUDENT_BELT
FROM STUDENT 



-- 심사비 납부
UPDATE TEST SET
TEST_PAY = 'Y'
WHERE STUDENT_NO = 1111
AND TEST_NM = '331회';


-- 심사비 미납자 조회
SELECT TEST_NM, TEST_DATE, STUDENT_NM
FROM TEST
JOIN STUDENT USING(STUDENT_NO)
WHERE TEST_PAY = 'N'
AND TEST_NM = '331회';

