-- 원생 테이블
-- 원생 번호, 이름, 성별, 주민등록번호, 입관일자, 띠
CREATE TABLE STUDENT(
	STUDENT_NO NUMBER PRIMARY KEY,
	STUDENT_NM VARCHAR2(30) NOT NULL,
	STUDENT_GENDER CHAR(1) CHECK( STUDENT_GENDER IN ('M', 'F') ),
	STUDENT_SSN CHAR(14),
	STUDENT_DATE DATE DEFAULT SYSDATE,
	STUDENT_BELT VARCHAR2(20)
);

COMMENT ON COLUMN STUDENT.STUDENT_NO IS '원생 번호';
COMMENT ON COLUMN STUDENT.STUDENT_NM IS '원생 이름';
COMMENT ON COLUMN STUDENT.STUDENT_GENDER IS '원생 성별';
COMMENT ON COLUMN STUDENT.STUDENT_SSN IS '원생 주민등록번호';
COMMENT ON COLUMN STUDENT.STUDENT_DATE IS '입관 일자';
COMMENT ON COLUMN STUDENT.STUDENT_BELT IS '원생 띠';

-- 원생 번호 시퀀스 생성
CREATE SEQUENCE SEQ_STUDENT_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

-- 원생 정보 추가 INSERT 
INSERT INTO "STUDENT"
VALUES('1111', '학생1', 'M', '150212-3012011', '2022-05-13', '흰띠')

INSERT INTO "STUDENT"
VALUES('2222', '학생2', 'F', '170212-4018511', '2022-09-18', '노란띠')

SELECT * FROM STUDENT;
